### ISSUE TITLE
Fix display bugs as per user feedback

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#101]
- [x] Add "Only 3rd-party listings" to empty amazon pricing situations
- [ ] Log out sometimes show up on two lines
- [x] The info table overlaps the book image on safari in search view
- [x] Carleton logo jiggles on hover
- [x] Text wrapping user view's book listings is screwy
- [x] When a description is expanded, sometimes the "less" text overlaps the end of the descriptions
- [x] Change mail icon to "make an offer" and a symbol
- [x] Remove ISBN from search suggestions; add tooltip

**Comment by dpikt** [comment]
See #133

**Comment by JSlote** [comment]
Still have to deal with the log out thing
