### ISSUE TITLE
Smoother redirect from accounts/dash to user page

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#112]

**Comment by dpikt** [comment]
This will probably require some rethinking of the way the states work right now.

**Comment by JSlote** [comment]
@dpikt What sort of smoothness are you thinking? Some sort of call does have to be made (and thus waiting time) to figure out the ID of the current user so that we can direct to the correct page

**Comment by dpikt** [comment]
Well right now it renders the account partial while redirecting, so the whole screen flashes. Ideally it wouldn't load any partial at all

**Comment by JSlote** [comment]
Fixed by #89
