### ISSUE TITLE
Re-write message-flashing method in the angular idiom

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#114]
Right now it uses jquery and directly modifies the HTML

**Comment by taoduo** [comment]
How to see a flash message?

**Comment by dpikt** [comment]
Go to /?flash=message. It's a little hard to see with the current styling but it's below the search bar.

**Comment by taoduo** [comment]
Do we want to get rid of jquery completely? There is some animations code over there, fade in / out. Do we substitude that with angular too?

**Comment by JSlote** [comment]
@taoduo for the code relevant to the flashing message, yes I think we should. There are other places in main.js where we can't substitute jquery easily (e.g., the `transist` function that I wrote), but we should strive to be "as angular as possible"

**Comment by taoduo** [comment]
The flash message function is made working without jquery. I introduced ng-animation module and the animation is done by css3 transition.

**Comment by dpikt** [comment]
Fixed in #131
