### ISSUE TITLE
Loading spinner sticks sometimes

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#115]
**How to Reproduce**
1. Search with any string of text. Type long enough so that multiple server calls are initiated
2. Click on a book before the spinner goes away

**Bug observed**
The spinner remains visible even after all calls are finished

**Comment by taoduo** [comment]
Fixed it by hiding the spinner upon going to details page.

**Comment by dpikt** [comment]
Fixed in #120
