### ISSUE TITLE
Recent Listings View

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#148]
- [x] Backend call with pagination (p.s., how does the frontend know when there aren't any more records available?)
- [x] Frontend

## Bugs
- [x] Transitions
- [x] Suddenly listing tables in detail view don't have header backgrounds
- [x] Modal gets hidden

**Comment by dpikt** [comment]
Implemented /listings/recent call. Re: your question, I don't know. You could use the /schoolStats call or I could implement a call just for counting listings

**Comment by JSlote** [comment]
Maybe could you return the total number in the response for listings/recent?

**Comment by dpikt** [comment]
Sure, I'll do that

**Comment by dpikt** [comment]
Pushed! Response now has a "numListings" attribute

**Comment by JSlote** [comment]
What glory! I'll start tonight.
