### ISSUE TITLE
Border radius still exists on mac selects

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#155]
![screen shot 2016-08-29 at 12 49 23 pm](https://cloud.githubusercontent.com/assets/7283471/18061115/1ab9321c-6de7-11e6-82fb-251a2a3f9746.png)

**Comment by JSlote** [comment]
@dpikt could you debug this a bit for me? Since the recent-listings PR, the dev branch should have a border-radius: 0 on the `select` element in _forms.scss. If it does and the border radius is still there, would you mind figuring out what style to add to what element to fix this? Thanks.

**Comment by dpikt** [comment]
Sure thing
