### ISSUE TITLE
Remove case-sensitivity on email address field in login

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#166]
Emails aren't case-sensitive, right? I can log in with `joseph.slote@gmail.com` but not `Joseph.slote@gmail.com`

**Comment by taoduo** [comment]
What about making all the email entries lower case on the backend during registration and login? When upper case letters are sent from the frontend, the backend turns the entries into lowercase and save / search in the database.

**Comment by JSlote** [comment]
That sounds good to me,  @taoduo. Want to take this one?

**Comment by taoduo** [comment]
@JSlote Yeah I can fix this one.

**Comment by taoduo** [comment]
@JSlote I think it's done.

**Comment by JSlote** [comment]
Done in #170
