### ISSUE TITLE
Old account was deleted

### ISSUE THREAD

**Issue by SchillerQuinn** [CarletonDevX/textbook-exchange#178]
I made an account with the username Schillerq@carleton.edu and added books to the waitlist. I got an email saying my book had shown up and when I went to log in it didn't let me. When I tried to reset my password it said my account didn't exist. I made a new account with schillerq@ and it allowed me to log in but it didn't have any of my old books saved. 

I don't want access to my old account or anything but this is a bug.

**Comment by dpikt** [comment]
Aha this was just plain unlucky! We recently changed the code to change all username requests to lowercase (#166) but I didn't think of what would happen if an uppercase username was already stored in the database. I'll go through the database and make sure there aren't any more uppercase usernames floating around.

Would you like me to give you access to the old account or delete it? Either option would only take a second.

**Comment by dpikt** [comment]
Just went thru the db, 5 people would've encountered the same bug! Thanks for reporting 😄

**Comment by SchillerQuinn** [comment]
Could you overwrite the new account with the old account?

**Comment by dpikt** [comment]
Sure thing, try logging in again and let me know if it worked!
