### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#25]

**Comment by JSlote** [comment]
@taoduo, @dpikt, not counting dev on the actual MVP, what server set-up work needs to be done to get this thing running somewhere where we can perform beta testing with students?

Also, who do you think would be good beta testers? I conveniently see approx 5 current students daily so I could start there...

**Comment by taoduo** [comment]
@JSlote @dpikt The short answer is that I do not really know about these. My node apps run on heroku but they are under the heroku domain name. If I want to use another domain name, I just redirect it to heroku. The URL changes and the users can see the redirection. We probably have better options.
As to testers, I have no idea either but I can invite some people I know to try this and give some feedback.

**Comment by dpikt** [comment]
http://162.243.21.124/ 😗

**Comment by dpikt** [comment]
@JSlote you own hitsthebooks.com right? We should get that configured to point to the site.

**Comment by JSlote** [comment]
Hahaha. That's great. Would it be possible to do a db.dropDatabase()? I think some schemas changed since I made an account on it (I keep causing internal server errors on registration/login attempts).

I'm also transferring ownership of hitsthebooks.com and "".org from DevX to me right now, so as soon as Namecheap gets its butt in gear I can point the DNS wherevs

**Comment by JSlote** [comment]
Ok domains are transferred. What DNS do I use @dpikt ?

**Comment by dpikt** [comment]
Ahh it's an issue with the emailing... gmail doesn't like getting a login from a digitalocean server. I'll see if I can fix it temporarily, although I want to switch to mailgun soon anyway.

**Comment by dpikt** [comment]
In regards to DNS 
![here's](https://cloud.githubusercontent.com/assets/7283471/17156085/eb2cdd2e-5355-11e6-8e4c-cfc8ebd9c800.png) what I did for a different domain

**Comment by dpikt** [comment]
I'll look into the subdomain thing

**Comment by dpikt** [comment]
AYY http://hitsthebooks.com/ is connected. I'll work on the email thing.

**Comment by JSlote** [comment]
Initial observations from other people:

 - One person thought he could only search by ISBNs because that was the placeholder text that had been chosen the first time he loaded the page
 - One person wanted to be able to click "10 listings available" so she could browse the books that are actually being offered by Carleton students

**Comment by JSlote** [comment]
Draft of an email to beta testers:

> Thanks so much for offering to beta test Carleton Hits the Books! We're nearly there, and we need your help to make sure the app is ready for prime time. Here's what would be most useful to us:
> 
> Go ahead and make an account and then poke around the site. So that beta testers will have a chance to interact with each other, we suggest adding listings and/or making offers on the following three books.
> - book 1
> - book 2
> - book 3
>
> Please document anything you find confusing, broken, or ugly. This includes both the mechanics of the site and the wording of any of the instructions and emails. If there is an error that you can reproduce by following a specific set of steps, please write those steps down. We need your findings by the end **Friday the 12th of August** in order to have time to fix/improve the application based on your comments. Please take only as much time as you have; we understand the end of the summer is a very busy time. Any comments or observations, no matter how small will be helpful to us.
>
> Again, thank you so very much for your kind assistance. We're planning on launching on August 22nd (shh) so we're very excited.

@taoduo , @dpikt , thoughts?

**Comment by dpikt** [comment]
Looks great to me!

**Comment by dpikt** [comment]
One thing- you should include a mention of *where* they should send their feedback. Are we sending these from a single address or from each of our addresses?

**Comment by JSlote** [comment]
I thought we could all send them to our buds & solicit feedback directly. But we could do it more formally too. I just think the personal touch will get more personal responses, which is what we want. What do you think?

**Comment by dpikt** [comment]
Ok so maybe we can put this formal thing in a pdf and attach it to our emails? That way we can write a personal message on top of it if need be.

**Comment by dpikt** [comment]
And include a dank logo in the pdf maybe

**Comment by dpikt** [comment]
Let's make a list of the people we're planning on inviting (up to 5 is a good number) so there aren't overlaps.

Mine are:
- Grace Black
- WIll French
- Joe Brommel
- Raven Pillmann
- Charlie Imhoff

**Comment by JSlote** [comment]
Other feelers are out, but have guaranteed 

- Patrick O'Reilly
- Violet Brown
- Caleb Braun

**Comment by JSlote** [comment]
[htb_beta_testing.pdf](https://github.com/CarletonDevX/textbook-exchange/files/414255/htb_beta_testing.pdf)

**Comment by dpikt** [comment]
App is live at https://fierce-brook-14047.herokuapp.com!
@taoduo @JSlote let's send our emails

**Comment by JSlote** [comment]
User testing initiated
