### ISSUE TITLE
User Details/Dashboard View

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#27]
- [x] Fix watchlist table bottom border
- [x] Make listings management work
- [x] Fix book list bottom border
- [x] Make watchlist management work
- [x] Make email settings changing work
- [x] Make "Dashboard" link redirect to own user page
- [x] Add password & name changing area
- [x] Style avatar changin
- [x] Style bio
- [x] Add logout button

**Comment by JSlote** [comment]
(fixes are on PR #42 )

**Comment by JSlote** [comment]
so close it's tasty

**Comment by dpikt** [comment]
Let's consider this finished
