### ISSUE TITLE
Registration Flow

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#30]
### Implement two new API calls & get a verification link workin'

- [x] /api/requestPasswordReset: begins the password reset process by sending an email to the user asking if they do indeed wish to reset their password
- [x] /api/resendVerification: resends the verification email
- [x] Get verification link working

### Cases at the login/register screen

- Logging in, but wrong password: give the user an opportunity to begin the password reset process
- Logging in, not registered: server responds with 401 (not authorized).
- Logging in, registered, but not verified: server responds with 400 (bad request) and we tell the user "There's an unverified account using that email already. Resend verification link?"
- Registering, but the email address is already registered but not verified: ignore the extant registration and just overwrite it as if it were a new registration
- Registering but already verified: server responds with 400 (bad request) and we tell the user "sorry, there's already an account associated with that email address"

### How the password reset process will work:

- When the user mistypes his or her password, we will give them a link to start the reset process.
- If they click the link, we'll send them an email asking if they really want to reset their password with a unique link
- If they click this unique link, we'll reset this password to a random temporary password
- We will then send them another email with this temporary password and tell them to change it ASAP in their account settings

**Comment by dpikt** [comment]
I'll work on that verification link.

**Comment by dpikt** [comment]
#38

**Comment by dpikt** [comment]
Do we have a way to flash a success message after redirecting to the homepage?

**Comment by JSlote** [comment]
@dpikt not as far as I know. What were you imagining? I'll take a look at the PR ASAP...

**Comment by JSlote** [comment]
@taoduo I updated the description of this issue as per @dpikt's and my conversation last night. What do you think?

**Comment by dpikt** [comment]
Would something like res.redirect("/?flash=message") work? And we'll have angular parse the query and display it?

**Comment by JSlote** [comment]
@dpikt Yea, that should work. And we'll need to ask them to log in again, right?

**Comment by dpikt** [comment]
The verify link will also log them in

**Comment by taoduo** [comment]
@JSlote Sorry. I did not see the question mark in the post. I think the registration flow is pretty reasonable. I have setup the basic structure of the frontend today.

**Comment by JSlote** [comment]
Hey @taoduo I took a look at the stuff on your branch and it looks good! I think now we're waiting on @dpikt to change the server responses and write those two other api requests.

**Comment by dpikt** [comment]
Server responses changed, api requests in progress

**Comment by dpikt** [comment]
#40

**Comment by dpikt** [comment]
Almost done! pending changes to #47

**Comment by JSlote** [comment]
Hey y'all, I went ahead and took a look at (then merged) #47. So I *think* we're good. @dpikt or @taoduo, I'll leave it to one of you to confirm the done-ness of this issue :)

**Comment by dpikt** [comment]
Just tested it, here are two thoughts:
- When login is successful, the login/register popup view should close
- When I try to register an existing username, it doesn't seem to flash a message
@taoduo could you make these changes?

**Comment by dpikt** [comment]
It also doesn't flash a message when I provide invalid input.

**Comment by taoduo** [comment]
@dpikt It is fixed. Since it is just two small issues, I merged it myself. Now it closes the modal and flash the messages.

**Comment by dpikt** [comment]
Awesome!
