### ISSUE TITLE
Make sure everyone has the same secret-config

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#37]

**Comment by JSlote** [comment]
wat

**Comment by dpikt** [comment]
Make sure everyone has the same secret-config

**Comment by dpikt** [comment]
¯\_(ツ)_/¯

**Comment by JSlote** [comment]
but how which wat do i do to complete the task cuz this is in the milestone apparently. who has correct copy

**Comment by dpikt** [comment]
It's more of a reminder than anything. But I'll send you mine and we can compare

**Comment by JSlote** [comment]
Sweet. I've replaced mine; @taoduo please confirm that you have the latest version (I emailed you) and we can close the issue

**Comment by taoduo** [comment]
Thanks. I got mine too.

**Comment by JSlote** [comment]
Great! Closed
