### ISSUE TITLE
Switch to mailgun?

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#45]

**Comment by dpikt** [comment]
@JSlote can you send me the credentials for modifying the DNS records? I need them to set up mailgun

**Comment by JSlote** [comment]
Unfortunately i don't think I should cuz it's my personal account and high
security pw :// HOWEVER if you make a namecheap account, go into personal
settings, security, and turn on "allow invitation to manage" and then send
me your user name, I can make you a manager on the domain!

**Comment by dpikt** [comment]
Haha we have different admin styles 
![screen shot 2016-07-26 at 10 35 24 pm](https://cloud.githubusercontent.com/assets/7283471/17162140/53ae4574-5381-11e6-83c6-3e50ef1eb798.png) will do

**Comment by dpikt** [comment]
#51
