### ISSUE TITLE
Refactor listings and offers

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#46]
There's duplicate data being stored in the db, I need to figure out the best way to handle this using mongo

**Comment by JSlote** [comment]
Ah this may explain why I've been accidentally corrupting some users' info... If can reproduce the bug I'll let you know

**Comment by dpikt** [comment]
Haha yikes

**Comment by dpikt** [comment]
Arrays to factor out:
book.subscribers
user.reports
user.offers
user.subscriptions

**Comment by dpikt** [comment]
I want to do this before we freeze an "official" schema

**Comment by dpikt** [comment]
Completed in #121
