### ISSUE TITLE
Incomplete amazon info corrupts user and breaks everything

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#56]
**Steps to reproduce:**
1. Go to http://carleton.localhost:1337/book/1555535445
2. Add a listing
3. Click on your name in the listing you added to go to your user page

**Bug observed**
500 internal server error

**Comment by dpikt** [comment]
lol lemme check it out

**Comment by JSlote** [comment]
May be related to #46

**Comment by JSlote** [comment]
No it should work on dev. Is it not?

**Comment by dpikt** [comment]
Dunno j wonderin

**Comment by dpikt** [comment]
#57

**Comment by dpikt** [comment]
The bug originated from the fact that the book wasn't being saved. So when the backend tried to inject books into listings for the user page, the book wasn't in the database to do it. Fixed by allowing sellingPrice to be null in amazonInfo.

**Comment by JSlote** [comment]
Well squashed
