### ISSUE TITLE
Handle empty search

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#61]
Try navigating to http://carleton.localhost:1337/search for giggles

**Comment by dpikt** [comment]
This also happens if you click the search box from the user view

**Comment by dpikt** [comment]
I think it would be better behavior just to have an undefined search take you back to the main page.

**Comment by JSlote** [comment]
Oh yea I saw that. Giggles indeed. I think it didn't used to do this, but I don't remember (I probably broke it). The proper behavior is to keep the search overlay up but to have the text go back to "I want to find or list a book" or whatever.

**Comment by dpikt** [comment]
Aha

**Comment by taoduo** [comment]
I got the version on the dev branch. 
I saw the problem by going to http://carleton.localhost:1337/search but I can not reproduce the error on the user view. 
Clicking the search box does not do anything and the search procedure is always protected by checking whether $scope.searchInput is empty. It does not do anything if it is empty.
By the way, the searching gets very slow. There is a long delay between searches. Is that expected?

**Comment by dpikt** [comment]
To reproduce the user view error, I navigated directly to a user view (eg put http://carleton.localhost:1337/user/:id in the url bar) then clicked the search input. Does it happen for you in that case?

Also, I've noticed the slow search times too. I don't know where that's coming from but I'll look into it.

**Comment by taoduo** [comment]
@dpikt yeah I see. I created a pull request and fixed it there. Can you verify it?

**Comment by dpikt** [comment]
#63
