### ISSUE TITLE
Create prettier/better emails

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#64]
- [x] watchlist
- [x] undercut
- [x] newPassword
- [x] requestPassword
- [x] offer
- [x] registration

**Comment by JSlote** [comment]
@dpikt Any more details on what you were thinking?

**Comment by dpikt** [comment]
Well there are three parts by my count. First of all, some of the links in the emails are broken, so those need to be functional. Then we need to copyedit them and make them friendlier/more understandable. Then we should use html/css to style them nicely, perhaps inserting a logo before the email (think campaign monitor stuff). I think we need an internal stylesheet for that,so I was thinking of editing the readEmail function in emails.controllers.js to append a stylesheet from a css file onto to each email.

**Comment by dpikt** [comment]
Emails to revamp:
- [ ] watchlist
- [ ] undercut
- [ ] newPassword
- [ ] offer
- [ ] registration

**Comment by dpikt** [comment]
In progress on dpikt/better-emails

**Comment by JSlote** [comment]
@dpikt this done?

**Comment by dpikt** [comment]
Fixed in #83
