### ISSUE TITLE
Change response code of validation errors

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#69]
It also results in a long validation error output on the server console. Is this how it's supposed to work?

**Comment by dpikt** [comment]
Yes, that's how it works. Maybe we should change the error code though.

**Comment by JSlote** [comment]
The internet told me it should be a 422; e.g., http://www.restpatterns.org/HTTP_Status_Codes/422_-_Unprocessable_Entity

**Comment by dpikt** [comment]
That's a rare one! Should I make all validation errors return a 422?

**Comment by JSlote** [comment]
I think so? What have you been using?

**Comment by dpikt** [comment]
I've made all mongoose errors return a 500. Clearly that doesn't always make sense!

**Comment by dpikt** [comment]
#72
