### ISSUE TITLE
UI Tweaks for Beta

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#73]
- [x] Bump little toolbar above the header when the browser window is too narrow
- [x] Change cursor on all link hovers (#72)
- [x] Make popups (eg login view) overlay existing views instead of replacing them
- [x] Decide on style of loading animation for the main search then implement it
- [x] Flash a message when the verification link is clicked

**Comment by JSlote** [comment]
Fixed by #81
