### ISSUE TITLE
On search results page, logging out and in again causes freeze

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#78]

**Comment by taoduo** [comment]
What do you mean by freeze? The search results disappeared but if you change the search input, it still works. Does it mean we want the search results stay there?

**Comment by dpikt** [comment]
Hi duo, sorry for the late response. Yes ideally we want the search results to stay there. Also the search input wasn't working for me but that might not still be the case.

**Comment by taoduo** [comment]
Hey @dpikt, I pulled the newest version on dev. This problem have been fixed by you guys. lol

**Comment by dpikt** [comment]
Haha ok!
