### ISSUE TITLE
Renting a book for $20 results in an internal server error

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#87]
**How to reproduce**

1. Go to https://fierce-brook-14047.herokuapp.com/book/0495108162
2. Log in
3. Click add listing
4. Change the renting price to `20`
5. Click List

**Bug Observed**
500 internal server error that results in the frontend not updating itself. However, if you manually refresh the page it shows the listing. The `rentingPrice` gets sent as a string, so that may be part of it.

**Comment by dpikt** [comment]
@JSlote this one was damn sneaky. Turns out it was a bug in the way undercut emails were being sent.

**Comment by dpikt** [comment]
Fixed in #106
