### ISSUE TITLE
Split login/register into two buttons/views

### ISSUE THREAD

**Issue by dpikt** [CarletonDevX/textbook-exchange#89]
Instead of having one button on the header called "Sign In or Register", we should have two buttons, "Sign In" and "Register"  that each lead to their respective views.

**Comment by taoduo** [comment]
Hey, it seems a .env file is needed to run the server locally now. I do not have it so it throws error "Must set env variables!".

**Comment by dpikt** [comment]
Oh yeah! I'll email you

**Comment by taoduo** [comment]
I forgot this... It has been done in the pull request.
